export const CHANGE_SEARCH_TERM = 'CHANGE_SEARCH_TERM';
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SET_ACTIVE_ID = 'SET_ACTIVE_ID';